### ISSUE TITLE
No styling

### ISSUE THREAD

**Issue by TarikHuber** [aabedraba/aabedraba.com#1]
Could you at least add a little bit of css and style...

**Comment by aabedraba** [comment]
There is.

**Comment by TarikHuber** [comment]
No there is no...

**Comment by aabedraba** [comment]
@TarikHuber 
https://github.com/aabedraba/aabedraba.com/blob/master/styles/globals.css
https://github.com/aabedraba/aabedraba.com/blob/master/pages/social.tsx#L21-L26

**Comment by TarikHuber** [comment]
no

**Comment by aabedraba** [comment]
Yes.

**Comment by TarikHuber** [comment]
![FB_IMG_1619396318575.jpg](https://user-images.githubusercontent.com/11230962/116014488-d27fcb00-a635-11eb-98f6-3525cf27179b.jpg)

**Comment by aabedraba** [comment]
There's no team here, It's just me. I don't need any designer.

**Comment by TarikHuber** [comment]
![photo_2021-04-24_18-30-42](https://user-images.githubusercontent.com/11230962/116038768-286e6600-a66a-11eb-9eaf-c9439c3be153.jpg)

**Comment by aabedraba** [comment]
HAHAHAHAHA exactly
